### ISSUE TITLE
if __name__ == main

### ISSUE THREAD

**Issue by allburov** [devopshq/teamcitytools#4]
https://github.com/devopshq/teamcitytools/wiki/TeamCity-DevOps-runners-Main-Instruction
Скрипт не должен содержать область if name == "main", т. к. эти шаги не отрабатывают будучи запущенными в метараннерах на TeamCity.

Если используется simpleRunner - условия отрабатывает, пункт можно убрать

**Comment by Tim55667757** [comment]
Поправил
