### ISSUE TITLE
Translate instruction ru->en

### ISSUE THREAD

**Issue by Tim55667757** [devopshq/teamcitytools#5]
https://github.com/devopshq/teamcitytools/wiki/TeamCity-DevOps-runners-Main-Instruction need to be translated

**Comment by SAnCherepan** [comment]
Done: https://github.com/devopshq/teamcitytools/wiki/TeamCity-DevOps-runners-Main-Instruction-(en)

**Comment by Tim55667757** [comment]
Thanks :)
